const allQuestions = [
    { num: 1, q: "What is the form of government of the United States?", a: ["Republic", "Constitution-based federal republic", "Representative democracy"] },
    { num: 2, q: "What is the supreme law of the land?", a: ["Constitution", "U.S. Constitution", "The Constitution"] },
    { num: 3, q: "Name one thing the U.S. Constitution does.", a: ["Forms the government", "Defines powers of government", "Defines the parts of government", "Protects the rights of the people"] },
    { num: 4, q: "The U.S. Constitution starts with the words \"We the People.\" What does \"We the People\" mean?", a: ["Self-government", "Popular sovereignty", "Consent of the governed", "People should govern themselves", "Social contract"] },
    { num: 5, q: "How are changes made to the U.S. Constitution?", a: ["Amendments", "The amendment process"] },
    { num: 6, q: "What does the Bill of Rights protect?", a: ["The basic rights of Americans", "Rights of Americans", "The basic rights of people living in the United States", "Rights of people living in the United States"] },
    { num: 7, q: "How many amendments does the U.S. Constitution have?", a: ["Twenty-seven", "27"] },
    { num: 8, q: "Why is the Declaration of Independence important?", a: ["It says America is free from British control", "It says all people are created equal", "It identifies inherent rights", "It identifies individual freedoms"] },
    { num: 9, q: "What founding document said the American colonies were free from Britain?", a: ["Declaration of Independence", "The Declaration of Independence"] },
    { num: 10, q: "Name two important ideas from the Declaration of Independence and the U.S. Constitution.", a: ["Equality", "Liberty", "Social contract", "Natural rights", "Limited government", "Self-government"] },
    { num: 11, q: "The words \"Life, Liberty, and the pursuit of Happiness\" are in what founding document?", a: ["Declaration of Independence", "The Declaration of Independence"] },
    { num: 12, q: "What is the economic system of the United States?", a: ["Capitalism", "Free market economy", "Market economy"] },
    { num: 13, q: "What is the rule of law?", a: ["Everyone must follow the law", "Leaders must obey the law", "Government must obey the law", "No one is above the law"] },
    { num: 14, q: "Many documents influenced the U.S. Constitution. Name one.", a: ["Declaration of Independence", "Articles of Confederation", "Federalist Papers", "Anti-Federalist Papers", "Virginia Declaration of Rights", "Fundamental Orders of Connecticut", "Mayflower Compact", "Iroquois Great Law of Peace"] },
    { num: 15, q: "There are three branches of government. Why?", a: ["So one part does not become too powerful", "Checks and balances", "Separation of powers"] },
    { num: 16, q: "Name the three branches of government.", a: ["Legislative, executive, and judicial", "Congress, president, and the courts", "Legislative executive judicial"] },
    { num: 17, q: "The President of the United States is in charge of which branch of government?", a: ["Executive branch", "Executive"] },
    { num: 18, q: "What part of the federal government writes laws?", a: ["Congress", "U.S. Congress", "Legislature", "Legislative branch"] },
    { num: 19, q: "What are the two parts of the U.S. Congress?", a: ["Senate and House of Representatives", "Senate and House", "The Senate and the House of Representatives"] },
    { num: 20, q: "Name one power of the U.S. Congress.", a: ["Writes laws", "Declares war", "Makes the federal budget"] },
    { num: 21, q: "How many U.S. senators are there?", a: ["One hundred", "100"] },
    { num: 22, q: "How long is a term for a U.S. senator?", a: ["Six years", "6 years", "6"] },
    { num: 23, q: "Who is one of your state's U.S. senators now?", a: ["Alex Padilla", "Padilla", "Adam Schiff", "Schiff"] },
    { num: 24, q: "How many voting members are in the House of Representatives?", a: ["Four hundred thirty-five", "435"] },
    { num: 25, q: "How long is a term for a member of the House of Representatives?", a: ["Two years", "2 years", "2"] },
    { num: 26, q: "Why do U.S. representatives serve shorter terms than U.S. senators?", a: ["To more closely follow public opinion"] },
    { num: 27, q: "How many senators does each state have?", a: ["Two", "2"] },
    { num: 28, q: "Why does each state have two senators?", a: ["Equal representation for small states", "Equal representation", "The Great Compromise", "Connecticut Compromise"] },
    { num: 29, q: "Name your U.S. representative.", a: ["Nancy Pelosi", "Pelosi"] },
    { num: 30, q: "What is the name of the Speaker of the House of Representatives now?", a: ["Mike Johnson", "Johnson"] },
    { num: 31, q: "Who does a U.S. senator represent?", a: ["Citizens of their state", "People of their state", "All people in their state"] },
    { num: 32, q: "Who elects U.S. senators?", a: ["Citizens from their state", "Citizens of their state", "People of their state"] },
    { num: 33, q: "Who does a member of the House of Representatives represent?", a: ["Citizens in their congressional district", "Citizens in their district", "People from their congressional district", "People in their district"] },
    { num: 34, q: "Who elects members of the House of Representatives?", a: ["Citizens from their congressional district", "Citizens from their district"] },
    { num: 35, q: "Some states have more representatives than other states. Why?", a: ["Because of the state's population", "The state's population", "Because they have more people", "They have more people", "Population"] },
    { num: 36, q: "The President of the United States is elected for how many years?", a: ["Four years", "4 years", "Four", "4"] },
    { num: 37, q: "The President of the United States can serve only two terms. Why?", a: ["Because of the 22nd Amendment", "The 22nd Amendment", "22nd Amendment", "To keep the president from becoming too powerful"] },
    { num: 38, q: "What is the name of the President of the United States now?", a: ["Donald Trump", "Trump", "Joe Biden", "Biden"] },
    { num: 39, q: "What is the name of the Vice President of the United States now?", a: ["JD Vance", "Vance", "Kamala Harris", "Harris"] },
    { num: 40, q: "If the president can no longer serve, who becomes president?", a: ["The Vice President", "Vice President"] },
    { num: 41, q: "Name one power of the president.", a: ["Signs bills into law", "Vetoes bills", "Enforces laws", "Commander in Chief of the military", "Commander in Chief", "Chief diplomat", "Appoints federal judges"] },
    { num: 42, q: "Who is Commander in Chief of the U.S. military?", a: ["The President", "President"] },
    { num: 43, q: "Who signs bills to become laws?", a: ["The President", "President"] },
    { num: 44, q: "Who vetoes bills?", a: ["The President", "President"] },
    { num: 45, q: "Who appoints federal judges?", a: ["The President", "President"] },
    { num: 46, q: "The executive branch has many parts. Name one.", a: ["President", "Cabinet", "Federal departments and agencies"] },
    { num: 47, q: "What does the President's Cabinet do?", a: ["Advises the President"] },
    { num: 48, q: "What are two Cabinet-level positions?", a: ["Attorney General", "Secretary of Agriculture", "Secretary of Commerce", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury", "Secretary of Veterans Affairs", "Secretary of Defense", "Vice President"] },
    { num: 49, q: "Why is the Electoral College important?", a: ["It decides who is elected president", "It provides a compromise between the popular election of the president and congressional selection"] },
    { num: 50, q: "What is one part of the judicial branch?", a: ["Supreme Court", "Federal Courts"] },
    { num: 51, q: "What does the judicial branch do?", a: ["Reviews laws", "Explains laws", "Resolves disputes about the law", "Decides if a law goes against the Constitution"] },
    { num: 52, q: "What is the highest court in the United States?", a: ["Supreme Court", "The Supreme Court"] },
    { num: 53, q: "How many seats are on the Supreme Court?", a: ["Nine", "9"] },
    { num: 54, q: "How many Supreme Court justices are usually needed to decide a case?", a: ["Five", "5"] },
    { num: 55, q: "How long do Supreme Court justices serve?", a: ["For life", "Life", "Lifetime appointment", "Until retirement"] },
    { num: 56, q: "Supreme Court justices serve for life. Why?", a: ["To be independent of politics", "To be independent", "To limit outside political influence", "To limit outside influence"] },
    { num: 57, q: "Who is the Chief Justice of the United States now?", a: ["John Roberts", "Roberts"] },
    { num: 58, q: "Name one power that is only for the federal government.", a: ["Print paper money", "Mint coins", "Declare war", "Create an army", "Make treaties", "Set foreign policy"] },
    { num: 59, q: "Name one power that is only for the states.", a: ["Provide schooling and education", "Provide protection", "Provide safety", "Give a driver's license", "Approve zoning and land use"] },
    { num: 60, q: "What is the purpose of the 10th Amendment?", a: ["Powers not given to the federal government belong to the states or to the people"] },
    { num: 61, q: "Who is the governor of your state now?", a: ["Gavin Newsom", "Newsom"] },
    { num: 62, q: "What is the capital of your state?", a: ["Sacramento"] },
    { num: 63, q: "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.", a: ["Citizens eighteen and older can vote", "You don't have to pay a poll tax to vote", "Any citizen can vote", "Women and men can vote", "A male citizen of any race can vote"] },
    { num: 64, q: "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?", a: ["Citizens", "Citizens of the United States", "U.S. citizens"] },
    { num: 65, q: "What are three rights of everyone living in the United States?", a: ["Freedom of expression", "Freedom of speech", "Freedom of assembly", "Freedom to petition the government", "Freedom of religion", "The right to bear arms"] },
    { num: 66, q: "What do we show loyalty to when we say the Pledge of Allegiance?", a: ["The United States", "United States", "The flag", "Flag"] },
    { num: 67, q: "Name two promises that new citizens make in the Oath of Allegiance.", a: ["Give up loyalty to other countries", "Defend the Constitution", "Obey the laws of the United States", "Serve in the military if needed", "Serve in the military", "Serve the nation if needed", "Serve the nation", "Be loyal to the United States"] },
    { num: 68, q: "How can people become United States citizens?", a: ["Be born in the United States", "Naturalize", "Derive citizenship"] },
    { num: 69, q: "What are two examples of civic participation in the United States?", a: ["Vote", "Run for office", "Join a political party", "Help with a campaign", "Join a civic group", "Join a community group", "Give an elected official your opinion on an issue", "Contact elected officials", "Support or oppose an issue or policy", "Write to a newspaper"] },
    { num: 70, q: "What is one way Americans can serve their country?", a: ["Vote", "Pay taxes", "Obey the law", "Serve in the military", "Run for office", "Work for local, state, or federal government"] },
    { num: 71, q: "Why is it important to pay federal taxes?", a: ["Required by law", "All people pay to fund the federal government", "Required by the Constitution", "Civic duty"] },
    { num: 72, q: "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.", a: ["Required by law", "Civic duty", "Makes the draft fair if needed"] },
    { num: 73, q: "The colonists came to America for many reasons. Name one.", a: ["Freedom", "Political liberty", "Religious freedom", "Economic opportunity", "Escape persecution"] },
    { num: 74, q: "Who lived in America before the Europeans arrived?", a: ["American Indians", "Native Americans"] },
    { num: 75, q: "What group of people was taken and sold as slaves?", a: ["Africans", "People from Africa"] },
    { num: 76, q: "What war did the Americans fight to win independence from Britain?", a: ["American Revolution", "The American Revolutionary War", "The Revolutionary War", "Revolutionary War", "War for American Independence", "War for Independence"] },
    { num: 77, q: "Name one reason why the Americans declared independence from Britain.", a: ["High taxes", "Taxation without representation", "British soldiers stayed in Americans' houses", "They did not have self-government", "Boston Massacre", "Boston Tea Party", "Tea Act", "Stamp Act", "Sugar Act", "Townshend Acts", "Intolerable Acts", "Coercive Acts"] },
    { num: 78, q: "Who wrote the Declaration of Independence?", a: ["Thomas Jefferson", "Jefferson"] },
    { num: 79, q: "When was the Declaration of Independence adopted?", a: ["July 4, 1776", "1776"] },
    { num: 80, q: "The American Revolution had many important events. Name one.", a: ["Battle of Bunker Hill", "Bunker Hill", "Declaration of Independence", "Washington Crossing the Delaware", "Battle of Trenton", "Battle of Saratoga", "Saratoga", "Valley Forge", "Battle of Yorktown", "Yorktown", "British surrender at Yorktown"] },
    { num: 81, q: "There were 13 original states. Name five.", a: ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"] },
    { num: 82, q: "What founding document was written in 1787?", a: ["U.S. Constitution", "Constitution", "The Constitution"] },
    { num: 83, q: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", a: ["James Madison", "Madison", "Alexander Hamilton", "Hamilton", "John Jay", "Jay", "Publius"] },
    { num: 84, q: "Why were the Federalist Papers important?", a: ["They helped people understand the Constitution", "They supported passing the Constitution"] },
    { num: 85, q: "Benjamin Franklin is famous for many things. Name one.", a: ["Founded the first free public libraries", "First Postmaster General of the United States", "Helped write the Declaration of Independence", "Inventor", "U.S. diplomat"] },
    { num: 86, q: "George Washington is famous for many things. Name one.", a: ["Father of Our Country", "First president of the United States", "General of the Continental Army", "President of the Constitutional Convention"] },
    { num: 87, q: "Thomas Jefferson is famous for many things. Name one.", a: ["Writer of the Declaration of Independence", "Third president of the United States", "Doubled the size of the United States", "Louisiana Purchase", "First Secretary of State", "Founded the University of Virginia", "Writer of the Virginia Statute on Religious Freedom"] },
    { num: 88, q: "James Madison is famous for many things. Name one.", a: ["Father of the Constitution", "Fourth president of the United States", "President during the War of 1812", "One of the writers of the Federalist Papers"] },
    { num: 89, q: "Alexander Hamilton is famous for many things. Name one.", a: ["First Secretary of the Treasury", "One of the writers of the Federalist Papers", "Helped establish the First Bank of the United States", "Aide to General George Washington", "Member of the Continental Congress"] },
    { num: 90, q: "What territory did the United States buy from France in 1803?", a: ["Louisiana Territory", "Louisiana"] },
    { num: 91, q: "Name one war fought by the United States in the 1800s.", a: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"] },
    { num: 92, q: "Name the U.S. war between the North and the South.", a: ["The Civil War", "Civil War"] },
    { num: 93, q: "The Civil War had many important events. Name one.", a: ["Battle of Fort Sumter", "Fort Sumter", "Emancipation Proclamation", "Battle of Vicksburg", "Vicksburg", "Battle of Gettysburg", "Gettysburg", "Sherman's March", "Surrender at Appomattox", "Appomattox", "Battle of Antietam", "Antietam", "Sharpsburg", "Lincoln was assassinated"] },
    { num: 94, q: "Abraham Lincoln is famous for many things. Name one.", a: ["Freed the slaves", "Emancipation Proclamation", "Saved the Union", "Preserved the Union", "Led the United States during the Civil War", "16th president of the United States", "Delivered the Gettysburg Address"] },
    { num: 95, q: "What did the Emancipation Proclamation do?", a: ["Freed the slaves", "Freed slaves in the Confederacy", "Freed slaves in the Confederate states", "Freed slaves in most Southern states"] },
    { num: 96, q: "What U.S. war ended slavery?", a: ["The Civil War", "Civil War"] },
    { num: 97, q: "What amendment says all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are U.S. citizens?", a: ["14th Amendment", "The 14th Amendment", "Fourteenth Amendment"] },
    { num: 98, q: "When did all men get the right to vote?", a: ["After the Civil War", "During Reconstruction", "With the 15th Amendment", "1870"] },
    { num: 99, q: "Name one leader of the women's rights movement in the 1800s.", a: ["Susan B. Anthony", "Elizabeth Cady Stanton", "Sojourner Truth", "Harriet Tubman", "Lucretia Mott", "Lucy Stone"] },
    { num: 100, q: "Name one war fought by the United States in the 1900s.", a: ["World War I", "World War II", "Korean War", "Vietnam War", "Persian Gulf War", "Gulf War"] },
    { num: 101, q: "Why did the United States enter World War I?", a: ["Because Germany attacked U.S. civilian ships", "Because Germany attacked U.S. ships", "To support the Allied Powers", "To oppose the Central Powers"] },
    { num: 102, q: "When did all women get the right to vote?", a: ["1920", "After World War I", "With the 19th Amendment"] },
    { num: 103, q: "What was the Great Depression?", a: ["Longest economic recession in modern history"] },
    { num: 104, q: "When did the Great Depression start?", a: ["The Great Crash", "1929", "Stock market crash of 1929"] },
    { num: 105, q: "Who was president during the Great Depression and World War II?", a: ["Franklin Roosevelt", "Roosevelt", "FDR"] },
    { num: 106, q: "Why did the United States enter World War II?", a: ["Bombing of Pearl Harbor", "Pearl Harbor", "Japanese attacked Pearl Harbor", "To support the Allied Powers", "To oppose the Axis Powers"] },
    { num: 107, q: "Dwight Eisenhower is famous for many things. Name one.", a: ["General during World War II", "President at the end of the Korean War", "34th president of the United States", "Signed the Federal-Aid Highway Act of 1956", "Created the Interstate System"] },
    { num: 108, q: "Who was the United States' main rival during the Cold War?", a: ["Soviet Union", "USSR", "Russia"] },
    { num: 109, q: "During the Cold War, what was one main concern of the United States?", a: ["Communism", "Nuclear war"] },
    { num: 110, q: "Why did the United States enter the Korean War?", a: ["To stop the spread of communism"] },
    { num: 111, q: "Why did the United States enter the Vietnam War?", a: ["To stop the spread of communism"] },
    { num: 112, q: "What did the civil rights movement do?", a: ["Fought to end racial discrimination"] },
    { num: 113, q: "Martin Luther King, Jr. is famous for many things. Name one.", a: ["Fought for civil rights", "Worked for equality for all Americans", "Worked to ensure that people would not be judged by the color of their skin but by the content of their character"] },
    { num: 114, q: "Why did the United States enter the Persian Gulf War?", a: ["To force the Iraqi military from Kuwait"] },
    { num: 115, q: "What major event happened on September 11, 2001 in the United States?", a: ["Terrorists attacked the United States", "Terrorists took over two planes and crashed them into the World Trade Center in New York City", "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia", "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania"] },
    { num: 116, q: "Name one U.S. military conflict after the September 11, 2001 attacks.", a: ["Global War on Terror", "War on Terror", "War in Afghanistan", "War in Iraq"] },
    { num: 117, q: "Name one American Indian tribe in the United States.", a: ["Apache", "Blackfeet", "Cayuga", "Cherokee", "Cheyenne", "Chippewa", "Choctaw", "Creek", "Crow", "Hopi", "Huron", "Inupiat", "Lakota", "Mohawk", "Mohegan", "Navajo", "Oneida", "Onondaga", "Pueblo", "Seminole", "Seneca", "Shawnee", "Sioux", "Teton", "Tuscarora"] },
    { num: 118, q: "Name one example of an American innovation.", a: ["Light bulb", "Automobile", "Cars", "Internal combustion engine", "Skyscrapers", "Airplane", "Assembly line", "Landing on the moon", "Integrated circuit"] },
    { num: 119, q: "What is the capital of the United States?", a: ["Washington, D.C.", "Washington D.C.", "Washington"] },
    { num: 120, q: "Where is the Statue of Liberty?", a: ["New York Harbor", "New York", "Liberty Island", "New Jersey", "Near New York City", "On the Hudson River"] },
    { num: 121, q: "Why does the flag have 13 stripes?", a: ["Because there were 13 original colonies", "Because the stripes represent the original colonies", "13 original colonies"] },
    { num: 122, q: "Why does the flag have 50 stars?", a: ["Because there is one star for each state", "Because each star represents a state", "Because there are 50 states", "50 states", "One for each state"] },
    { num: 123, q: "What is the name of the national anthem?", a: ["The Star-Spangled Banner", "Star-Spangled Banner"] },
    { num: 124, q: "The Nation's first motto was \"E Pluribus Unum.\" What does that mean?", a: ["Out of many, one", "We all become one"] },
    { num: 125, q: "What is Independence Day?", a: ["A holiday to celebrate U.S. independence from Britain", "A holiday to celebrate U.S. independence", "The country's birthday"] },
    { num: 126, q: "Name three national U.S. holidays.", a: ["New Year's Day", "Martin Luther King, Jr. Day", "Presidents Day", "Washington's Birthday", "Memorial Day", "Juneteenth", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving Day", "Thanksgiving", "Christmas Day", "Christmas"] },
    { num: 127, q: "What is Memorial Day?", a: ["A holiday to honor soldiers who died in military service"] },
    { num: 128, q: "What is Veterans Day?", a: ["A holiday to honor people in the U.S. military", "A holiday to honor people who have served in the U.S. military"] }
];
